### ISSUE TITLE
Fireface 802: `input:mic-power` and `input:mic-instrument` don't appear to be working as intended

### ISSUE THREAD

**Issue by Schroedingers-Cat** [alsa-project/snd-firewire-ctl-services#44]
The Fireface 802 has a three-state LED per Mic input indicating the status of the input. It can be in the states `off`, `48V` or `Inst`. These states are taken from the manual: https://archiv.rme-audio.de/download/fface_802_e.pdf (page 57). The manual doesn't mention that these states are mutually exclusive, it also doesn't mention that the LED will show a different colour for `48V`and `Inst.`. If both settings are off, the LED will stop emitting light.  

This repo's service exposes these settings of the Fireface 802 via the `input:mic-power` (48V) and the `input:mic-instrument` (Inst.) mixer property. However, setting any of these options doesn't cause the LED on the mic inputs to emit light.  
Furthermore, this repo's service allows to set both properties `input:mic-power` and `input:mic-instrument` to true at the same time, which is not supported by the RME driver on Windows. For instance, setting the `input:mic-power` property of channel 9 to true should set the `input:mic-instrument` property of channel 9 to false if it was true before.

**Comment by takaswie** [comment]
Hi @Schroedingers-Cat 

I apologize long delay to start working for the issue, but I need to take my time for the
other relevant problems...

> However, setting any of these options doesn't cause the LED on the mic inputs to emit light.

Indeed. I find the misprogramming that the index of channel in generated command is invalid. The index should start at 8, but currently at 0:

https://github.com/alsa-project/snd-firewire-ctl-services/blob/master/protocols/fireface/src/latter.rs#L721

I push a remote branch as topic to the issue. The fix is at the top-most commit of the branch:
https://github.com/alsa-project/snd-firewire-ctl-services/tree/topic/ff/fix-mic-inputs

If I can still get your help, would I ask you to test it and confirm the above bug is fixed?

> Furthermore, this repo's service allows to set both properties `input:mic-power` and `input:mic-instrument` to true at the same time, which is not supported by the RME driver on Windows. For instance, setting the `input:mic-power` property of channel 9 to true should set the `input:mic-instrument` property of channel 9 to false if it was true before.

Exactly. As long as I tested, enabling instrument mode turns off phantom powering,
while the control elements added by the service program doesn't handle the case
property. Let me leave it in my TODO list.

Thanks

**Comment by takaswie** [comment]
I file the fix at #144 .

**Comment by takaswie** [comment]
#44 is merged. Let me close the issue since expecting no reactions.

**Comment by Schroedingers-Cat** [comment]
I sold my Firewire card and cable because I experienced audio artifacts with this driver, so I cannot test/verify the changes anymore. Really sorry, but great to hear that it's fixed now!
