### ISSUE TITLE
M-Audio ProFire Lightbridge: Kernel panic - not syncing: Fatal local machine check 

### ISSUE THREAD

**Issue by jpnielsen** [alsa-project/snd-firewire-ctl-services#55]
Trying to revive old "M-Audio ProFire LightBridge" interface.

It's attached using adat to one PreSonus Digimax FS (I also have a Behringer Ultragain Pro-8 and an Expert Sleepers ES-3 with adat)
no-name Firewire pci-e interface (VIA VT6307 + asmedia asm1083 ICs) 
motherboard is an ASRock Phantom Gaming 4 / AMD X570
CPU is a Ryzen 7 3700x
RAM is 2x16GB Corsair CMK32GX4M2B3200C16 

uname -a
Linux debian 5.10.0-8-amd64 #1 SMP Debian 5.10.46-1 (2021-06-24) x86_64 GNU/Linux

lspci |grep -i firewire
05:00.0 FireWire (IEEE 1394): VIA Technologies, Inc. VT6306/7/8 [Fire II(M)] IEEE 1394 OHCI Controller (rev 80)

I get a Kernel Panic when I turn on the "M-Audio ProFire LightBridge".
    
[ 96.930836] mce: [Hardware Error]: CPU 6: Machine Check Exception: 7 Bank 0: bc002800000c0135 
[ 96.930837] mce: [Hardware Error]: RIP 10:ffffffffc025b08a> {get_cycle_time+0x2a/0x120 [firewire_ohci]}
[ 96.930838] mce: [Hardware Error]: TSC 69e4ebbb40 ADDR fc7000c0 MISC d01a0ffe00000000 IPID b000000000 
[ 96.930840] mce: [Hardware Error]: PROCESSOR 2:870f10 TIME 1626800481 SOCKET 0 APIC c microcode 8701021 
[ 96.930840] Kernel panic - not syncing: Fatal local machine check 
[ 96.931077] Kernel Offset: 0x2b000000 from 0xffffffff81000000 (relocation range: 0xffffffff80000000-0xffffffffbfffffff) 

The "M-Audio ProFire LightBridge" crashes Windows 10 too using the M-Audio drivers for windows 7 SP1 (released 06/02/2012) 
I can set the sample rate and sync and change the LED's accordingly on the ProFire. But when i try sending audio to it, windows crashes.
https://m-audio.com/support/download/drivers/firewire-installer-6.0.4-driver-5.10.0.5061

I don't have other firewire devices for testing the VIA firewire adapter.

Am I missing something obvious?

Any tips on how to proceed ?

**Comment by takaswie** [comment]
Hi,

Thanks for the report.

At first, the aim of this repository is to maintain service programs which communicates to
the device by packet transmission with short content. The programs are just userspace
applciations, thus they can not bring kernel crash, in theory.

The support for your device is split to two parts; the service program and in-kernel driver
(snd-bebob) for continuous packet transmission to transfer PCM frames and MIDI messages.
If your issue was relevant to my work, it shall be related to the latter. I maintain the latter in
below repository for backport purpose:

 * https://github.com/takaswie/snd-firewire-improve

Please file it to the above repository, instead.

**Comment by jpnielsen** [comment]
OK,
https://github.com/takaswie/snd-firewire-improve/issues/36
