### ISSUE TITLE
where is enum 'Analog-B-0' being defined?

### ISSUE THREAD

**Issue by dreamcat4** [alsa-project/snd-firewire-ctl-services#92]
Hello again,
This is for saffire-pro 40 (dice)... When i run the following cmdline:

```sh
amixer -c2 sget stream-source,0 
Simple mixer control 'stream-source',0
  Capabilities: enum
  Items: 'None' 'Analog-B-0' 'Analog-B-1' 'Analog-B-2' 'Analog-B-3' 'Analog-B-4' 'Analog-B-5' 'S/PDIF-coax-0' 'S/PDIF-coax-1' 'ADAT-0' 'ADAT-1' 'ADAT-2' 'ADAT-3' 'ADAT-4' 'ADAT-5' 'ADAT-6' 'ADAT-7' 'S/PDIF-opt-0' 'S/PDIF-opt-1' 'Mixer-0' 'Mixer-1' 'Mixer-2' 'Mixer-3' 'Mixer-4' 'Mixer-5' 'Mixer-6' 'Mixer-7' 'Mixer-8' 'Mixer-9' 'Mixer-10' 'Mixer-11' 'Mixer-12' 'Mixer-13' 'Mixer-14' 'Mixer-15'
  Item0: 'Analog-B-0'
  Item1: 'Analog-B-1'
  Item2: 'Analog-B-2'
  Item3: 'Analog-B-3'
  Item4: 'Analog-B-4'
  Item5: 'Analog-B-5'
  Item6: 'None'
  Item7: 'None'
  Item8: 'S/PDIF-coax-0'
  Item9: 'S/PDIF-coax-1'
  Item10: 'ADAT-0'
  Item11: 'ADAT-1'
  Item12: 'ADAT-2'
  Item13: 'ADAT-3'
  Item14: 'None'
  Item15: 'None'
  Item16: 'None'
  Item17: 'None'
  Item18: 'None'
  Item19: 'None'
  Item20: 'None'
  Item21: 'None'
  Item22: 'None'
  Item23: 'None'
  Item24: 'None'
  Item25: 'None'
```

it seems like only the 1st 6 anaglog input channels are being routed. This seems to concur with my early initial test (which is not verified again)... where i did not get loopback working on the last 2 analog inputs (channels 7 and 8). But there was a working signal on the 1st six (6) audio input channels.

So it seems like this is the setting for routing those inputs... at least until I do some further testing to be sure. And double check.

Anyhow I was just wondering why is only defined as ENUM values the 1st 6 channels here

```sh
  Item0: 'Analog-B-0'
  Item1: 'Analog-B-1'
  Item2: 'Analog-B-2'
  Item3: 'Analog-B-3'
  Item4: 'Analog-B-4'
  Item5: 'Analog-B-5'
  Item6: 'None'
  Item7: 'None'
```

and why is not exist in the interface those last 2 channels. Which would otherwise be expected as further enum label `Analog-B-6` and `Analog-B-7`.

I can see here in the rust code a reference to the string `stream-source` = `const ROUTER_CAP_SRC_NAME` being defined here:

https://github.com/alsa-project/snd-firewire-ctl-services/blob/master/libs/dice/runtime/src/tcd22xx_ctl.rs#L207

so it looks like `new` and `old` are the string on cmdline

https://github.com/alsa-project/snd-firewire-ctl-services/blob/master/libs/dice/runtime/src/tcd22xx_ctl.rs#L369

which then must be convert to actual enum (or `uint32` / `<u32>` whatever)

https://github.com/alsa-project/snd-firewire-ctl-services/blob/master/libs/dice/runtime/src/tcd22xx_ctl.rs#L494

and you `get_vals()` from the `self` object or wherever is being held some lookup table.

However I cannot actually find where is the enum definition (maybe in a C lib after bindings / GIR ?). To then see and know why is not exist those last 2 input channels (of 7 and 8 on the saffire pro 40 hardware, they are physical analog XLR inputs).

It would be nice to know! Many thanks

**Comment by takaswie** [comment]
Hi,

> it seems like only the 1st 6 anaglog input channels are being routed. This seems to concur with my early initial test (which is not verified again)... where i did not get loopback working on the last 2 analog inputs (channels 7 and 8). But there was a working signal on the 1st six (6) audio input channels.
>
> So it seems like this is the setting for routing those inputs... at least until I do some further testing to be sure. And double check.

As long as I remember, the loopback function of Focusrite Saffire 40 is implemented by using
internal mixer function of TCD2220 ASIC. It's not by any analog circuit.

When configuring source ports of mixer and select any output of mixer in the stream-source control, you can receive the signals in PCM capture stream.

But as you note, I have less care of physical analog XLR inputs. We need to investigate how the device handles these inputs.

I'll tell you where the string `Analog-B-0` comes from.

The ASIC have two lines (I2S or PDM) for analog inputs, each of which has maximum 8 channels. In Focusrite Saffire 40, 2nd line (`ins1`) is just used, against our expectation.
I have no idea why the first line (`ins0`) is not used.

In protocol crate (`dice-protocols`), you can see implementation of `Tcd22xxSpecOperation` for `SPro40Protocol` has an input entry with `SrcBlkId::Ins1` and 6 channels:
 * https://github.com/alsa-project/snd-firewire-ctl-services/blob/master/libs/dice/protocols/src/focusrite/spro40.rs#L21

In `Tcd22xxSpecOperation::src_blk_label()`, "Analog-B-{}" is used to generate label for the `SrcBlkId::Ins1`:

 * https://github.com/alsa-project/snd-firewire-ctl-services/blob/master/libs/dice/protocols/src/tcat/tcd22xx_spec.rs#L168

In runtime crate (`dice-runtime`), `Tcd22xxSpecOperation::src_blk_label()` is used by `RouterCtlOperation::add_an_elem_for_src()` via trait `T` parameter:

 * https://github.com/alsa-project/snd-firewire-ctl-services/blob/master/libs/dice/runtime/src/tcd22xx_ctl.rs#L448

The trait is implemented as generic for the structure which implements `Tcd22xxCtlOperation` trait:

 * https://github.com/alsa-project/snd-firewire-ctl-services/blob/master/libs/dice/runtime/src/tcd22xx_ctl.rs#L530

The `Tcd22xxCtlOperation` trait is implemented to `SPro40Tcd22xxCtl` with `SPro40Protocol` parameter:

 * https://github.com/alsa-project/snd-firewire-ctl-services/blob/master/libs/dice/runtime/src/focusrite/spro40_model.rs#L262

I'm sorry but I am currently a bit busy to clean up crates developed in the project for publishment in crates.io.

 * https://crates.io/users/takaswie

Any supplemental work for the issue is postponed.

**Comment by dreamcat4** [comment]
ah ok! thank you @takaswie it was indeed a good help. and also was nice to hear what was the other focus currently

**Comment by dreamcat4** [comment]
so you do not need to be distracted by this 2nd response. not important. just for fun. if curious:

my friend, you did leave a clue for me. to go and dig further. since after the definition of 6 input channel there is then remaining 2 put there for spdif...

by coincidence, another owner of this saffire pro 40. he mentioned that one of the later on firmware updates was issued to 'fix spidif port not working / to get it working'.  so perhaps that matter is related with the location of the spdif port in the firmware being different than on the hardware bus / wiring

my interface has last firmware (fully updated). so it should be after that firmware bugfix. maybe i can also probe the board. to see which gpio pins are connecte. to check against the datasheet for where is the real wiring goes. if can be checked physical pinout for the `ins1` i2s bus in the datasheet. (if those pins are not remapped by the asic / in the firmware)

but could be faster for me to just try recompiling that definition in the rust (which you provided above):

https://github.com/alsa-project/snd-firewire-ctl-services/blob/master/libs/dice/protocols/src/focusrite/spro40.rs#L18-L31

personally i do not use or need spdif coax port for anything (because it also has adat). so maybe i can just remove and delete spdif (`count: 2`) definition entirely. and then extend the analog from 6 to 8. recompile, and find out what happens.

come to think of it, perhaps the asic might want to do some special handling of spdif channels. to be able reconfigure the physical adat optical port (it can be set as either adat or spdif). so that feature might require some extra signal routing idk. and that itself might be a reason for confusion or mixups as to which spdif is going to where. and how it is being labelled. idk yet.

so i will look into further, try to keep learning and find out more in detail. maybe not interest to other devices. when specific only to the saffire pro 40 alone.

anyhow so many thanks here the gratitude. your comments and manner were very kind. a good day

**Comment by dreamcat4** [comment]
> The ASIC have two lines (I2S or PDM) for analog inputs, each of which has maximum 8 channels. In Focusrite Saffire 40, 2nd line (ins1) is just used, against our expectation.
I have no idea why the first line (ins0) is not used.

ok... have done a bit of further testing now. Just enough to confirm that on this `ins1`... it is indeed true my suspicion. That in fact all 8 of those channels are being used for routing the bank of 8 analog input channels. No spdif there.

So where you have defined the 2 channels of spdif coax (after the first 6)... 

Before issuing the next command. I have setup signal on the last 2 analog inputs hardware channels (marked 7 and 8 on the hardware). Which is receiving in my DAW. Being sent through the firewire cable to the PC.

Then if I remove those default spdif assignment (`S/PDIF-coax-0 S/PDIF-coax-1` --> set them to `None None`), it should disable those marked as spdif. With the exposed s contents amixer api (this command)...

```sh
amixer -c0 sset stream-source,0 Analog-B-0 Analog-B-1 Analog-B-2 Analog-B-3 Analog-B-4 Analog-B-5 None None
```

Those last 2 analog input channels stops. No more audio comes to the PC. And when I put them back:

```sh
amixer -c0 sset stream-source,0 Analog-B-0 Analog-B-1 Analog-B-2 Analog-B-3 Analog-B-4 Analog-B-5 S/PDIF-coax-0 S/PDIF-coax-1
```

Then the audio playback is resumed. For those analog input channels. And I have not touched listened on the SPDIF port. So it is not known yet (for spdif) what the spdif is doing.

But clearly we need to change the `6` assignment --> `8`. For those analog. So that they are not mis-labeled. Which is the easy part.

The more difficult question then, where is the SPDIF coax input (2 ch). If defined in other place. If the `ins1` has only maximum 8 channels. Then maybe it cannot fit anymore at the very end of `ins1` bank.

Ran out of time, to do anymore. But perhaps it would help to open up and probe the PCB ? To see where the traces goes to/from the coax spdif port? (to which exact GPIO pins on the DICE chip).

That will have to wait until next time. Maybe during next week.
