### ISSUE TITLE
Fireface 802 : headphone outputs not working

### ISSUE THREAD

**Issue by francoisromain** [alsa-project/snd-firewire-ctl-services#95]
Hello, 

First thank you again for this great project. 
I use the driver with a fireface 802 and 2x 8 channels input adat converters (aphex 142) and it works really well. 

I think I noticed a bug on the headphone output: 
- headphone output 1L has no signal at all whatever the output we use. 
- headphone output 1R takes the signal from output `2`, which is the speaker output and should not be routed to the headphone.
- headphone outputs 2 have no signal at all whatever the output.

**Comment by francoisromain** [comment]
I also noticed a shift in the inputs number : 
- adat input 25 should be 27
- adat input 26 should be 25
- adat input 27 should be 26

**Comment by takaswie** [comment]
Hi @francoisromain,

I'm sorry the long delay to reply. I started to work for the service program including protocol implementation for RME Fireface series.

> I think I noticed a bug on the headphone output:
> 
>     * headphone output 1L has no signal at all whatever the output we use.
> 
>     * headphone output 1R takes the signal from output `2`, which is the speaker output and should not be routed to the headphone.
> 
>     * headphone outputs 2 have no signal at all whatever the output.

I guess that something unexpected in your system since I could not regenerate the issue. The channel position 8/9 and 10/11 in PCM frame go to HP output 0/1 and 2/3, as I expected.

> I also noticed a shift in the inputs number :
> 
>     * adat input 25 should be 27
> 
>     * adat input 26 should be 25
> 
>     * adat input 27 should be 26

I could not regenerate it as well. I guess that configuration of `mixer:stream-source-gain` control element seems to be invalid for channel position 25/26/27 (or application side). The control element is to set signal sources for captured PCM frame. For example, you can direct physical
ADAT input ch4 to ch0 in PCM frame so that applications can retrieve the ADAT audio signal in the first channel of PCM frame.

Anyway I welcome any help for the service program. Please check #44 as well in which an apparent bug was reported and going to be fixed.

Thanks in advance.

**Comment by takaswie** [comment]
Oops, I misinterpreted current implementation...

```
I guess that something unexpected in your system since I could not regenerate the issue. The channel position 8/9 and 10/11 in PCM frame go to HP output 0/1 and 2/3, as I expected.
```

For headphone output, the setting of `mixer:stream-source-gain` is available. The 8/9/10/11 (index begins at 0) mixer corresponds to headphone 0/1/2/3. The 8/9/10/11 (index begins at 0) channel expresses the channel of PCM frame.

> I could not regenerate it as well. I guess that configuration of `mixer:stream-source-gain` control element seems to be invalid for channel position 25/26/27 (or application side). The control element is to set signal sources for captured PCM frame. For example, you can direct physical ADAT input ch4 to ch0 in PCM frame so that applications can retrieve the ADAT audio signal in the first channel of PCM frame.

The control element is just for playback PCM substream, thus the above is wrong. I guess
that it is application matter to handle PCM channel position.

Regards

**Comment by francoisromain** [comment]
I resetted the interface from TotalMix on a mac 
and switched from Ubuntu to Fedora (linux 6.1.14, pipewire 0.3.66). 

Now the headphones and ADAT outputs works fine. It was probably due to a misconfiguration on my side.
I close the issue. 

* * *

But I still can not use the fireface 802 in firewire because of latency. 
I have to use it in usb. 
I open another issue about that. 

Thank you very much for your work.
